name:                proto-lens-grpc
version:             0.1
github:              "FormationAI/proto-lens-grpc"
license:             BSD3
author:              Formation
copyright:           (c) 2017-2019 Formation

extra-source-files:
- README.md
- ChangeLog.md
- third_party/googleapis/google/rpc/status.proto

description: gRPC support for proto-lens using grpc-haskell-core.

dependencies:
- base >= 4.7 && < 5

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup == 0.4.*

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - async
    - bytestring
    - case-insensitive
    - containers
    - exceptions
    - grpc-haskell-core
    - lens
    - lens-labels
    - proto-lens
    - proto-lens-runtime
    - proto-lens-protobuf-types
    - retry
    - text
    - these
    - transformers
  exposed-modules:
    - Data.ProtoLens.GRPC.Client
    - Data.ProtoLens.GRPC.Data.ExtensibleRecord
    - Data.ProtoLens.GRPC.LowLevelMagic
    - Data.ProtoLens.GRPC.Magic
    - Data.ProtoLens.GRPC.Server
    - Proto.Google.Rpc.Status
